/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejercicio3;

import static ejercicio3.Articulos.connection;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Mikel
 * @version 1.0 beta
 * 
 */
public final class Pedidos extends javax.swing.JFrame {

    /**
     * Variable que guarda la consulta principal de pedidos
     */
    static public ResultSet r;
    
    /**
     * Variable que guarda la consulta lineas de pedido
     */
    static public ResultSet r3;
    

    /**
     * método constructor de la sección pedidos
     * @throws SQLException 
     */
    public Pedidos() throws SQLException {
        initComponents();
        this.setLocationRelativeTo(null);
                cancelarl.setVisible(false);
                guardarl.setVisible(false);
        cancelar.setVisible(false);
        guardar.setVisible(false);
        String url = "jdbc:mysql://localhost:3306/entornos";
        String user = "root";
        String pass = "";
        Connection connection = DriverManager.getConnection(url, user, pass);

        Statement s = connection.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
        String query = "select * from Pedidos, lineas_pedido";
        r = s.executeQuery(query);
        r.first();
        numero.setText(r.getString("num_pedido"));
        fecha.setText(r.getString("fecha"));

        //lineas de pedidos
        Npedido.setText(r.getString("NUM_PEDIDO"));
        Nlinea.setText(r.getString("NUM_LINEA"));
        articulo.setText(r.getString("ARTICULO"));
        cantidad.setText(r.getString("CANTIDAD"));
        descuento.setText(r.getString("DESCUENTO"));
        importe.setText(r.getString("IMPORTE"));

        //llamada combobox//
        connection = DriverManager.getConnection(url, user, pass);
        String query2 = "select nombre from clientes";
        ResultSet r2;
        Statement s2 = connection.createStatement();
        r2 = s2.executeQuery(query2);
        DefaultComboBoxModel value1 = new DefaultComboBoxModel();

        while (r2.next()) {
            value1.addElement(r2.getString("NOMBRE"));
        }
        cliente.setModel(value1);

        cliente.setSelectedItem(getNomCliente(r.getString("CLIENTE")));
        
        String numeropedido = (numero.getText());
        getlinea(numeropedido);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     *
     * @return
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        panel1 = new java.awt.Panel();
        panel2 = new java.awt.Panel();
        fecha3 = new javax.swing.JTextField();
        fecha4 = new javax.swing.JTextField();
        fecha7 = new javax.swing.JTextField();
        inicio2 = new javax.swing.JButton();
        inicio4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        numero = new javax.swing.JTextField();
        fecha = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        guardar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        editar = new javax.swing.JButton();
        nuevo = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        previous = new javax.swing.JButton();
        next = new javax.swing.JButton();
        last = new javax.swing.JButton();
        inicio = new javax.swing.JButton();
        first = new javax.swing.JButton();
        cliente = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        Nlinea = new javax.swing.JTextField();
        Npedido = new javax.swing.JTextField();
        cantidad = new javax.swing.JTextField();
        descuento = new javax.swing.JTextField();
        importe = new javax.swing.JTextField();
        articulo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        siguientel = new javax.swing.JButton();
        anteriorl = new javax.swing.JButton();
        lastl = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        iniciol = new javax.swing.JButton();
        nuevol = new javax.swing.JButton();
        editarl = new javax.swing.JButton();
        guardarl = new javax.swing.JButton();
        deletel = new javax.swing.JButton();
        cancelarl = new javax.swing.JButton();

        jButton3.setText("jButton1");

        jButton7.setText("jButton1");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        fecha3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        fecha4.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        fecha7.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        inicio2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        inicio2.setText("Inicio");
        inicio2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        inicio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicio2ActionPerformed(evt);
            }
        });

        inicio4.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        inicio4.setText("Inicio");
        inicio4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        inicio4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicio4ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        jLabel1.setText("LINEAS DEL PEDIDO");

        numero.setEditable(false);
        numero.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        numero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroActionPerformed(evt);
            }
        });

        fecha.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel2.setText("Número");

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel3.setText("Fecha");

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel4.setText("Artículo");

        guardar.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        guardar.setText("Guardar");
        guardar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0)));
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });

        cancelar.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        cancelar.setText("Cancelar");
        cancelar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        editar.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        editar.setText("Editar");
        editar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));
        editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarActionPerformed(evt);
            }
        });

        nuevo.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        nuevo.setText("Nuevo");
        nuevo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 0)));
        nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoActionPerformed(evt);
            }
        });

        delete.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        delete.setText("Eliminar");
        delete.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        previous.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        previous.setText("Anterior");
        previous.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        previous.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousActionPerformed(evt);
            }
        });

        next.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        next.setText("Siguiente");
        next.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });

        last.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        last.setText("Último");
        last.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        last.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastActionPerformed(evt);
            }
        });

        inicio.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        inicio.setText("Inicio");
        inicio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicioActionPerformed(evt);
            }
        });

        first.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        first.setText("Primero");
        first.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        first.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstActionPerformed(evt);
            }
        });

        cliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteActionPerformed(evt);
            }
        });

        Nlinea.setEditable(false);
        Nlinea.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        Npedido.setEditable(false);
        Npedido.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        cantidad.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        descuento.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        importe.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        articulo.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel5.setText("Cliente");

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel6.setText("Cantidad");

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel7.setText("Importe");

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel8.setText("Nº Linea");

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel9.setText("Descuento");

        jLabel10.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel10.setText("Nº Pedido");

        siguientel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        siguientel.setText("Siguente ");
        siguientel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        siguientel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguientelActionPerformed(evt);
            }
        });

        anteriorl.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        anteriorl.setText("Anterior");
        anteriorl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        anteriorl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anteriorlActionPerformed(evt);
            }
        });

        lastl.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lastl.setText("Última");
        lastl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lastl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastlActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        jLabel11.setText("PEDIDOS");

        iniciol.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        iniciol.setText("Primera");
        iniciol.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        iniciol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciolActionPerformed(evt);
            }
        });

        nuevol.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        nuevol.setText("Nuevo");
        nuevol.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 0)));
        nuevol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevolActionPerformed(evt);
            }
        });

        editarl.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        editarl.setText("Editar");
        editarl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));
        editarl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarlActionPerformed(evt);
            }
        });

        guardarl.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        guardarl.setText("Guardar");
        guardarl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0)));
        guardarl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarlActionPerformed(evt);
            }
        });

        deletel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        deletel.setText("Eliminar");
        deletel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        deletel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletelActionPerformed(evt);
            }
        });

        cancelarl.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        cancelarl.setText("Cancelar");
        cancelarl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        cancelarl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarlActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(numero, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(178, 178, 178)
                                .addComponent(editar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(80, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82))))
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(first, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(previous, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(next, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(articulo, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel6)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(8, 8, 8)
                                            .addComponent(jLabel7)))
                                    .addGap(31, 31, 31)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(descuento, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(importe, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Npedido, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Nlinea, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(last, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(anteriorl, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(siguientel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(iniciol, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lastl, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nuevol, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(editarl, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(deletel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(guardarl, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cancelarl, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(48, 48, 48)
                    .addComponent(jLabel5)
                    .addContainerGap(648, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(182, 182, 182)
                    .addComponent(jLabel11)
                    .addContainerGap(435, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numero, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(first, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(previous, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(next, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(last, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Npedido, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel1))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nlinea, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(anteriorl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(siguientel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(iniciol, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lastl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nuevol, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editarl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(deletel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(guardarl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cancelarl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(articulo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(descuento, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(importe, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(246, 246, 246)
                    .addComponent(jLabel5)
                    .addContainerGap(569, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(jLabel11)
                    .addContainerGap(773, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
     /**
     * Metodo que toma el nombre del cliente y devuelve el código de este mismo.
     * 
     * @param nombre variable que contiene el nombre del cliente.
     * @return dni - variable que contiene el código del cliente.
     * 
     */
    public String getDni(String nombre) {

        String dni = "";

        try {
            String url = "jdbc:mysql://localhost:3306/entornos";
            String user = "root";
            String pass = "";
            Connection connection = DriverManager.getConnection(url, user, pass);
            Statement s = connection.createStatement();
            String query2 = "select NIF FROM clientes where nombre='" + nombre + "'";
            ResultSet r2;
            r2 = s.executeQuery(query2);
            r2.first();
            dni = r2.getString("NIF");
        } catch (SQLException ex) {
            Logger.getLogger(Clientes.class.getName()).log(Level.SEVERE, null, ex);
        }
        return dni;
    }

     /**
      * Metodo que toma el dni cliente y devuelve el código de este mismo.
      * 
      * @param dni_cliente variable que contiene el dni del cliente
      * @return nombre - variable que contiene el nombre del cliente
      * 
      */
    
    
    public String getNomCliente(String dni_cliente) {

        String nombre = "";

        try {
            String url = "jdbc:mysql://localhost:3306/entornos";
            String user = "root";
            String pass = "";
            Connection connection = DriverManager.getConnection(url, user, pass);
            Statement s = connection.createStatement();
            String query2 = "select nombre FROM clientes where nif='" + dni_cliente + "'";
            ResultSet r2;
            r2 = s.executeQuery(query2);
            r2.first();
            nombre = r2.getString("NOMBRE");
        } catch (SQLException ex) {
            Logger.getLogger(Clientes.class.getName()).log(Level.SEVERE, null, ex);
        }
        return nombre;
    }

    
    /**
      * Metodo que toma el las lineas de un pedido a mostrar
      * 
      *@param numerodepedido - variable que contiene el códgo del pedido 
      */
    
    
    public void getlinea(String numeropedido) {

        try {

            String url = "jdbc:mysql://localhost:3306/entornos";
            String user = "root";
            String pass = "";
            Connection connection = DriverManager.getConnection(url, user, pass);
            Statement s = connection.createStatement();
            String query3 = "select NUM_PEDIDO, NUM_LINEA, ARTICULO, CANTIDAD, DESCUENTO, IMPORTE FROM lineas_pedido WHERE NUM_PEDIDO = '" + numeropedido + "'";
            
            r3 = s.executeQuery(query3);
            r3.first();
            Npedido.setText(r3.getString("NUM_PEDIDO"));
            Nlinea.setText(r3.getString("NUM_LINEA"));
            articulo.setText(r3.getString("ARTICULO"));
            cantidad.setText(r3.getString("CANTIDAD"));
            descuento.setText(r3.getString("DESCUENTO"));
            importe.setText(r3.getString("IMPORTE"));

        } catch (SQLException ex) {
            Logger.getLogger(Clientes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }


    private void numeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroActionPerformed

    private void firstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstActionPerformed
        // TODO add your handling code here:

        try {
            r.first();
            numero.setText(r.getString("num_pedido"));
            fecha.setText(r.getString("fecha"));
            cliente.setSelectedItem(getNomCliente(r.getString("CLIENTE")));

            String numeropedido = (numero.getText());
            getlinea(numeropedido);

            // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(Pedidos.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_firstActionPerformed

    private void previousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousActionPerformed
        // TODO add your handling code here:

        try {
            if (r.previous()) {
                numero.setText(r.getString("num_pedido"));
                fecha.setText(r.getString("fecha"));
                cliente.setSelectedItem(getNomCliente(r.getString("CLIENTE")));

                //lineas de pedido
                String numeropedido = (numero.getText());
                getlinea(numeropedido);

            }

            // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(Pedidos.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_previousActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        // TODO add your handling code here:

        try {
            if (r.next()) {
                numero.setText(r.getString("num_pedido"));
                fecha.setText(r.getString("fecha"));
                cliente.setSelectedItem(getNomCliente(r.getString("CLIENTE")));

                //lineas de pedido
                String numeropedido = (numero.getText());
                getlinea(numeropedido);

            }

            // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(Pedidos.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_nextActionPerformed

    private void lastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastActionPerformed
        // TODO add your handling code here:

        try {
            r.last();
            numero.setText(r.getString("num_pedido"));
            fecha.setText(r.getString("fecha"));
            cliente.setSelectedItem(getNomCliente(r.getString("CLIENTE")));

            String numeropedido = (numero.getText());
            getlinea(numeropedido);

            // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(Pedidos.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_lastActionPerformed

    private void inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicioActionPerformed
        // TODO add your handling code here:

        menu ped = new menu();
        ped.setLocationRelativeTo(null);
        this.setVisible(false);
        ped.setVisible(true);
    }//GEN-LAST:event_inicioActionPerformed

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        // TODO add your handling code here:

        try {
            String Vnumpedido, Vfecha, Vcliente;
            Vnumpedido = numero.getText();
            Vfecha = fecha.getText();
            Vcliente = (String) cliente.getSelectedItem();
            String url = "jdbc:mysql://localhost:3306/entornos";
            String user = "root";
            String pass = "";
            Connection connection = DriverManager.getConnection(url, user, pass);

            Statement s = connection.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
            String query = "insert pedidos values ('" + Vnumpedido + "','" + Vfecha + "','" + getDni(Vcliente) + "')";
            int resultado = s.executeUpdate(query);

            String query2 = "select * from pedidos";
            r = s.executeQuery(query2);
            r.first();
            numero.setText(r.getString("num_pedido"));
            fecha.setText(r.getString("fecha"));
            cliente.setSelectedItem(r.getString("cliente"));
            first.setVisible(true);
            next.setVisible(true);
            previous.setVisible(true);
            last.setVisible(true);
            editar.setVisible(true);
            nuevo.setVisible(true);
            cancelar.setVisible(false);
            guardar.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(Pedidos.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_guardarActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        // TODO add your handling code here:
        first.setVisible(true);
        next.setVisible(true);
        previous.setVisible(true);
        last.setVisible(true);
        editar.setVisible(true);
        nuevo.setVisible(true);
        cancelar.setVisible(false);
        guardar.setVisible(false);
        try {
            r.first();
            numero.setText(r.getString("num_pedido"));
            fecha.setText(r.getString("fecha"));
            cliente.setSelectedItem(r.getString("cliente"));
            numero.setEditable(false);
        } catch (SQLException ex) {
            Logger.getLogger(Pedidos.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_cancelarActionPerformed

    private void editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarActionPerformed
        // TODO add your handling code here:

        try {
            String Vnumpedido, Vfecha, Vcliente;
            Vnumpedido = numero.getText();
            Vfecha = fecha.getText();
            Vcliente = (String) cliente.getSelectedItem();
            String cliente = getDni(Vcliente);

            String url = "jdbc:mysql://localhost:3306/entornos";
            String user = "root";
            String pass = "";
            Connection connection = DriverManager.getConnection(url, user, pass);
            Statement s = connection.createStatement();
            String query = "update pedidos set FECHA='" + Vfecha + "',  CLIENTE='" + cliente + "' WHERE NUM_PEDIDO='" + Vnumpedido + "'";
            int resultado = s.executeUpdate(query);
            r.refreshRow();
        } catch (SQLException ex) {
            Logger.getLogger(Pedidos.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_editarActionPerformed

    private void nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoActionPerformed
        // TODO add your handling code here:
        first.setVisible(false);
        next.setVisible(false);
        previous.setVisible(false);
        last.setVisible(false);
        editar.setVisible(false);
        nuevo.setVisible(false);
        cancelar.setVisible(true);
        guardar.setVisible(true);
        numero.setEditable(true);
        numero.setText("");
        fecha.setText("");
        cliente.setSelectedItem("");


    }//GEN-LAST:event_nuevoActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:

        try {
            String Vnumpedido;
            Vnumpedido = numero.getText();

            String url = "jdbc:mysql://localhost:3306/entornos";
            String user = "root";
            String pass = "";
            Connection connection = DriverManager.getConnection(url, user, pass);

            Statement s = connection.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
            String query = "delete from pedidos where num_pedido=" + Vnumpedido;
            int resultado = s.executeUpdate(query);

            String query2 = "select * from pedidos";
            r = s.executeQuery(query2);
            r.first();
            numero.setText(r.getString("num_pedido"));
            fecha.setText(r.getString("fecha"));
            cliente.setSelectedItem(r.getString("cliente"));

            first.setVisible(true);
            next.setVisible(true);
            previous.setVisible(true);
            last.setVisible(true);
            editar.setVisible(true);
            nuevo.setVisible(true);
            cancelar.setVisible(false);
            guardar.setVisible(false);

        } catch (SQLException ex) {
            Logger.getLogger(Pedidos.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_deleteActionPerformed

    private void clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clienteActionPerformed

    private void siguientelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguientelActionPerformed

        try {
            if (r3.next()) {

                Npedido.setText(r3.getString("NUM_PEDIDO"));
                Nlinea.setText(r3.getString("NUM_LINEA"));
                articulo.setText(r3.getString("ARTICULO"));
                cantidad.setText(r3.getString("CANTIDAD"));
                descuento.setText(r3.getString("DESCUENTO"));
                importe.setText(r3.getString("IMPORTE"));
            }

            // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(Pedidos.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_siguientelActionPerformed

    private void inicio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicio2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inicio2ActionPerformed

    private void anteriorlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anteriorlActionPerformed
        // TODO add your handling code here:
        
        try {
            if (r3.previous()) {
                
                Npedido.setText(r3.getString("NUM_PEDIDO"));
                Nlinea.setText(r3.getString("NUM_LINEA"));
                articulo.setText(r3.getString("ARTICULO"));
                cantidad.setText(r3.getString("CANTIDAD"));
                descuento.setText(r3.getString("DESCUENTO"));
                importe.setText(r3.getString("IMPORTE"));

            }

            // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(Pedidos.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_anteriorlActionPerformed

    private void inicio4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicio4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inicio4ActionPerformed

    private void lastlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastlActionPerformed
        // TODO add your handling code here:
        try {
            r3.last();
                Npedido.setText(r3.getString("NUM_PEDIDO"));
                Nlinea.setText(r3.getString("NUM_LINEA"));
                articulo.setText(r3.getString("ARTICULO"));
                cantidad.setText(r3.getString("CANTIDAD"));
                descuento.setText(r3.getString("DESCUENTO"));
                importe.setText(r3.getString("IMPORTE"));
        } catch (SQLException ex) {
            Logger.getLogger(Pedidos.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_lastlActionPerformed

    private void iniciolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciolActionPerformed
        // TODO add your handling code here:
            try {
            r3.first();
            Npedido.setText(r3.getString("NUM_PEDIDO"));
                Nlinea.setText(r3.getString("NUM_LINEA"));
                articulo.setText(r3.getString("ARTICULO"));
                cantidad.setText(r3.getString("CANTIDAD"));
                descuento.setText(r3.getString("DESCUENTO"));
                importe.setText(r3.getString("IMPORTE"));
                
        } catch (SQLException ex) {
            Logger.getLogger(Pedidos.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_iniciolActionPerformed

    private void nuevolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevolActionPerformed
        // TODO add your handling code here:
        iniciol.setVisible(false);
        siguientel.setVisible(false);
        anteriorl.setVisible(false);
        lastl.setVisible(false);
        editarl.setVisible(false);
        nuevol.setVisible(false);
        cancelarl.setVisible(true);
        guardarl.setVisible(true);
        deletel.setVisible(false);
        
        Npedido.setEditable(false);
        Nlinea.setEditable(true);
        Nlinea.setText("");
        articulo.setText("");
        cantidad.setText("");
        descuento.setText("");
        importe.setText("");
        
        
    }//GEN-LAST:event_nuevolActionPerformed

    private void editarlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarlActionPerformed
        // TODO add your handling code here:
        try {
            String Vnumpedido, Vnumlinea, Vimporte, Vdescuento, Vcantidad, Varticulo;
            Vnumpedido= Npedido.getText();
            Vnumlinea= Nlinea.getText();
            Vimporte= importe.getText();
            Vdescuento= descuento.getText();
            Vcantidad= cantidad.getText();
            Varticulo= articulo.getText();  

            String url = "jdbc:mysql://localhost:3306/entornos";
            String user = "root";
            String pass = "";
            Connection connection = DriverManager.getConnection(url, user, pass);
            Statement s = connection.createStatement();
            String query = "update lineas_pedido set IMPORTE='" + Vimporte + "', DESCUENTO='" + Vdescuento + "', ARTICULO='" + Varticulo+ "',CANTIDAD='" + Vcantidad + "' WHERE NUM_LINEA='" + Vnumlinea + "'";
            int resultado = s.executeUpdate(query);
            
            String numeropedido= numero.getText();
            String query3 = "select NUM_PEDIDO, NUM_LINEA, ARTICULO, CANTIDAD, DESCUENTO, IMPORTE FROM lineas_pedido WHERE NUM_PEDIDO = '" + numeropedido + "'";
            
            r3 = s.executeQuery(query3);
            r3.first();
            Npedido.setText(r3.getString("NUM_PEDIDO"));
            Nlinea.setText(r3.getString("NUM_LINEA"));
            articulo.setText(r3.getString("ARTICULO"));
            cantidad.setText(r3.getString("CANTIDAD"));
            descuento.setText(r3.getString("DESCUENTO"));
            importe.setText(r3.getString("IMPORTE"));
            
        } catch (SQLException ex) {
            Logger.getLogger(Pedidos.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
    }//GEN-LAST:event_editarlActionPerformed

    private void guardarlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarlActionPerformed
        // TODO add your handling code here:
         try {

            String Vnumpedido, Vnumlinea, Vimporte, Vdescuento, Vcantidad, Varticulo;
            
            Vnumpedido= Npedido.getText();
            Vnumlinea= Nlinea.getText();
            Vimporte= importe.getText();
            Vdescuento= descuento.getText();
            Vcantidad= cantidad.getText();
            Varticulo= articulo.getText();  

            String url = "jdbc:mysql://localhost:3306/entornos";
            String user = "root";
            String pass = "";
            Connection connection = DriverManager.getConnection(url, user, pass);

            Statement s = connection.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
            
            String query = "insert lineas_pedido values ('" + Vnumlinea + "','" + Vnumpedido + "','" + Varticulo + "','" + Vcantidad + "','" + Vdescuento + "', '" + Vimporte + "')";
            int resultado = s.executeUpdate(query);

            String query2 = "select * from lineas_pedido";
            r = s.executeQuery(query2);
            r.first();

            Npedido.setText(r.getString("NUM_PEDIDO"));
            Nlinea.setText(r.getString("NUM_LINEA"));
            importe.setText(r.getString("IMPORTE"));
            descuento.setText(r.getString("DESCUENTO"));
            cantidad.setText(r.getString("CANTIDAD"));
            articulo.setText(r.getString("ARTICULO"));

            iniciol.setVisible(true);
            siguientel.setVisible(true);
            anteriorl.setVisible(true);
            lastl.setVisible(true);
            editarl.setVisible(true);
            nuevol.setVisible(true);
            cancelarl.setVisible(false);
            guardarl.setVisible(false);
            
            
            String numeropedido= numero.getText();
            String query3 = "select NUM_PEDIDO, NUM_LINEA, ARTICULO, CANTIDAD, DESCUENTO, IMPORTE FROM lineas_pedido WHERE NUM_PEDIDO = '" + numeropedido + "'";
            
            r3 = s.executeQuery(query3);
            r3.first();
            Npedido.setText(r3.getString("NUM_PEDIDO"));
            Nlinea.setText(r3.getString("NUM_LINEA"));
            articulo.setText(r3.getString("ARTICULO"));
            cantidad.setText(r3.getString("CANTIDAD"));
            descuento.setText(r3.getString("DESCUENTO"));
            importe.setText(r3.getString("IMPORTE"));

      

            
        } catch (SQLException ex) {
            Logger.getLogger(Pedidos.class.getName()).log(Level.SEVERE, null, ex);
        }
         
        
        
        
        
        
    }//GEN-LAST:event_guardarlActionPerformed

    private void deletelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletelActionPerformed
        // TODO add your handling code here:
        try {
            String Vnumpedido, Vnumlinea;
            Vnumpedido = Npedido.getText();
            Vnumlinea= Nlinea.getText();
            
            String url = "jdbc:mysql://localhost:3306/entornos";
            String user = "root";
            String pass = "";
            Connection connection = DriverManager.getConnection(url, user, pass);

            Statement s = connection.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
            String query = "delete from lineas_pedido where num_pedido='" + Vnumpedido + "' AND num_linea='" + Vnumlinea + "'";
            int resultado = s.executeUpdate(query);

            String numeropedido= numero.getText();
            String query3 = "select NUM_PEDIDO, NUM_LINEA, ARTICULO, CANTIDAD, DESCUENTO, IMPORTE FROM lineas_pedido WHERE NUM_PEDIDO = '" + numeropedido + "'";
            
            r3 = s.executeQuery(query3);
            r3.first();
            Npedido.setText(r3.getString("NUM_PEDIDO"));
            Nlinea.setText(r3.getString("NUM_LINEA"));
            articulo.setText(r3.getString("ARTICULO"));
            cantidad.setText(r3.getString("CANTIDAD"));
            descuento.setText(r3.getString("DESCUENTO"));
            importe.setText(r3.getString("IMPORTE"));

        } catch (SQLException ex) {
            Logger.getLogger(Pedidos.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_deletelActionPerformed

    private void cancelarlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarlActionPerformed
        // TODO add your handling code here:
            iniciol.setVisible(true);
            siguientel.setVisible(true);
            anteriorl.setVisible(true);
            lastl.setVisible(true);
            editarl.setVisible(true);
            nuevol.setVisible(true);
            cancelarl.setVisible(false);
            guardarl.setVisible(false);
            deletel.setVisible(true);
        try {
            r3.first();
            Npedido.setText(r3.getString("NUM_PEDIDO"));
            Nlinea.setText(r3.getString("NUM_LINEA"));
            articulo.setText(r3.getString("ARTICULO"));
            cantidad.setText(r3.getString("CANTIDAD"));
            descuento.setText(r3.getString("DESCUENTO"));
            importe.setText(r3.getString("IMPORTE"));
            
            
            
        } catch (SQLException ex) {
            Logger.getLogger(Pedidos.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_cancelarlActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Pedidos().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Pedidos.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField Nlinea;
    public static javax.swing.JTextField Npedido;
    private javax.swing.JButton anteriorl;
    public static javax.swing.JTextField articulo;
    private javax.swing.JButton cancelar;
    private javax.swing.JButton cancelarl;
    public static javax.swing.JTextField cantidad;
    private javax.swing.JComboBox<String> cliente;
    private javax.swing.JButton delete;
    private javax.swing.JButton deletel;
    public static javax.swing.JTextField descuento;
    private javax.swing.JButton editar;
    private javax.swing.JButton editarl;
    private javax.swing.JTextField fecha;
    private javax.swing.JTextField fecha3;
    private javax.swing.JTextField fecha4;
    private javax.swing.JTextField fecha7;
    private javax.swing.JButton first;
    private javax.swing.JButton guardar;
    private javax.swing.JButton guardarl;
    public static javax.swing.JTextField importe;
    private javax.swing.JButton inicio;
    private javax.swing.JButton inicio2;
    private javax.swing.JButton inicio4;
    private javax.swing.JButton iniciol;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton last;
    private javax.swing.JButton lastl;
    private javax.swing.JButton next;
    private javax.swing.JButton nuevo;
    private javax.swing.JButton nuevol;
    private javax.swing.JTextField numero;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    private javax.swing.JButton previous;
    private javax.swing.JButton siguientel;
    // End of variables declaration//GEN-END:variables

}
